[2023-04-19 19:32:14,314] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: PredictingPipeline.request_predictions_step manual__2023-04-19T19:32:13.335214+00:00 [queued]>
[2023-04-19 19:32:14,324] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: PredictingPipeline.request_predictions_step manual__2023-04-19T19:32:13.335214+00:00 [queued]>
[2023-04-19 19:32:14,324] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-04-19 19:32:14,324] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2023-04-19 19:32:14,324] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2023-04-19 19:32:14,334] {taskinstance.py:1264} INFO - Executing <Task(PredictionResquestsOperator): request_predictions_step> on 2023-04-19 19:32:13.335214+00:00
[2023-04-19 19:32:14,341] {standard_task_runner.py:52} INFO - Started process 1109 to run task
[2023-04-19 19:32:14,344] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'PredictingPipeline', 'request_predictions_step', 'manual__2023-04-19T19:32:13.335214+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/predict_pipeline.py', '--cfg-path', '/tmp/tmp85luqg54', '--error-file', '/tmp/tmp4qavdull']
[2023-04-19 19:32:14,344] {standard_task_runner.py:77} INFO - Job 49: Subtask request_predictions_step
[2023-04-19 19:32:14,391] {logging_mixin.py:109} INFO - Running <TaskInstance: PredictingPipeline.request_predictions_step manual__2023-04-19T19:32:13.335214+00:00 [running]> on host dfdc77248185
[2023-04-19 19:32:14,432] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-04-19 19:32:14,464] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=PredictingPipeline
AIRFLOW_CTX_TASK_ID=request_predictions_step
AIRFLOW_CTX_EXECUTION_DATE=2023-04-19T19:32:13.335214+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-19T19:32:13.335214+00:00
[2023-04-19 19:32:14,529] {connectionpool.py:811} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faa2cde21d0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /ping
[2023-04-19 19:32:17,546] {connectionpool.py:811} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faa45fff2d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /ping
[2023-04-19 19:32:18,250] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=PredictingPipeline, task_id=request_predictions_step, execution_date=20230419T193213, start_date=20230419T193214, end_date=20230419T193218
[2023-04-19 19:32:18,288] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-04-19 19:32:18,314] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
